### PR TITLE
feat: Add docs for create a personal discord bot and recommend IDE setting 

### PR DESCRIPTION
**Pull request by CrimsonNightZero**
## Why need this change? / Root cause: 
- WSA-Utopia-Discord-Bot kickoff
## Changes made:
- Readme
## Test Scope / Change impact:
-
235358947-98bb0de3-b406-47ea-9fb8-f930a453f3a9

### CODE REVIEW

**Review by Wally5077 — APPROVED** [review]
LGTM

**Review by hokou — APPROVED** [review]
LGTM

**Comment by hokou** [comment]
圖面的超連結建議改成參照
E:\xxx\docs\  => .\docs\

image

**Review by frankvicky — APPROVED** [review]
LGTM

**Pull request merged**
